### ISSUE TITLE
GIF creation throws error

### ISSUE THREAD

**Issue by mrprompt** [CroatianMeteorNetwork/cmn_binviewer#4]
When click on GIF button (Create animation session) thows an error about `imageio` absent in `FF_bin_suite.py` on line 465.

**Comment by dvida** [comment]
Hi,
you are probably missing the imageio library. Try doing:
pip install imageio

**Comment by dvida** [comment]
Have you tried following the troublehooting section in readme? Does this help:
sudo apt-get install python-imaging-tk

**Comment by epogrebnyak** [comment]
In a similar problem in helped to upgrade `pillow`: https://github.com/danijar/handout/issues/22#issuecomment-519453400

**Comment by dvida** [comment]
Thank you, I confirm that the problem on the Pi can be fixed by opening the terminal and running:
```
deactivate
sudo pip install imageio
sudo install --upgrade pillow
```
